### ISSUE TITLE
Syntax highlighting breaks after < and <= operators

### ISSUE THREAD

**Issue by tormol** [mathiasfrohlich/vscode-kotlin#31] opened 2018-11-01 20:00 UTC
![1 28 1 screenshot](https://user-images.githubusercontent.com/10460821/47875641-59fa7380-de17-11e8-9b12-9324ed0269c3.png)

[code](https://pl.kotl.in/SJ2JY0d2Q)

vscode version: 1.28.1 built from source
kotlin-language version: 1.7.0 (from marketplace)
OS: Ubuntu 18.04

**Comment by mondique** [comment] 2018-11-21 18:37
It seems that it thinks that < is the beginning of a scope (an opening brace). As you can see, it highlights the text after > and the original < is highlighted as the corresponding brace for the > sign.
(And by the way, the closing > sign was not shifted by me - I typed it at the beginning of the line - it was probably aligned with the line 2 containing "<")

vscode version: 1.29.1
Kotlin Language version: 1.7.0 (from marketplace)
OS: Windows 10 Pro version 1803

![capture](https://user-images.githubusercontent.com/4715017/48861551-dfe55b00-edd4-11e8-899f-ff3fd4b4e82f.PNG)

**Comment by valen214** [comment] 2019-03-04 18:00
`/syntaxes/Kotlin.tmLanguage: line 829` suggests the cause is '<' being captured as generic.begin

**Comment by wildlava** [comment] 2019-04-04 16:33
I can verify that temporarily changing the symbols for "<" and ">" on lines 831 and 841 of Kotlin.tmLanguage causes the problem to go away. It might work, therefore, just to remove the detection of the generic begin/end chars (at least as a stop-gap solution). But I am not sure of the exact changes to this file that would be required to do that.

**Closed** 2019-12-09 00:37 UTC

**Comment by Mithrandir2k18** [comment] 2020-02-10 09:18
Issue still present, check out [this file](https://github.com/RainwayApp/flutter_gamepad/blob/master/android/src/main/kotlin/com/example/flutter_gamepad/GamepadCache.kt), commit d2e703c
